name: netsci-gnn-linkpred
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.3.2
  - matplotlib=3.8.3
  - networkx=3.2.1
  - tqdm=4.66.2
  - pytorch=2.2.0
  - pyg  # meta-package do torch-geometric no conda
  - pip
  - pip:
      - torch-geometric==2.4.0
      - jupyter==1.0.0
      - jupyterlab==4.1.0
      - ipython==8.21.0
